version: "3.2"
services:
  zookeeper:
    image: zookeeper
    domainname: zookeeper
    networks:
    - zookeeper-network
    ports:
    - "2181:2181"
  dubbo-admin:
    image: akafra/dubbo-admin
    networks:
      - zookeeper-network
    depends_on:
      - zookeeper
    ports:
      - 8888:8080
networks:
  zookeeper-network:
