version: '2'
services:
  zookeeper:
    image: zookeeper
    networks:
      - dubbo-admin
    ports:
      - "2181:2181"
  dubbo-admin:
    image: akafra/dubbo-admin
    networks: 
      - dubbo-admin
    depends_on:
      - zookeeper
    ports:
      - "8888:8080"
networks:
  dubbo-admin:
