version: "3.2"
services:
  rabbitmq-server:
    image: rabbitmq:3.7
    networks:
      - mq
    ports:
      - "5672:5672"
    expose:
      - 5672
  management-server:
    image: rabbitmq:3-management
    networks:
      - mq
    ports:
      - "8070:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - 8070
networks:
  mq:
