version: "3.2"
services:
#  mq-service:
#    image: rabbitmq:3.7
#    networks:
#      - mq
#    ports:
#      - "5672:5672"
#    expose:
#      - 5672
  management-server:
    image: rabbitmq:3-management
    networks:
      - mq
    ports:
      - "8080:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: hello
    expose:
      - 8080
      - 5672
networks:
  mq: