version: "3.2"
services:
  mysql-service:
    image: mysql:5.7.23
    volumes:
      - mysql-data-5.7:/var/lib/mysql
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: hello
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - db
    ports:
      - "3306:3306"
volumes:
    mysql-data-5.7:
networks:
  db: